name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Set the permissions for GitHub token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'           # Java version to install
        distribution: 'temurin'      # Specify the Java distribution (e.g., temurin)
    - name: Build with Maven
      run: mvn -B package --file pom.xml
